import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-table',
  templateUrl: './app-table.component.html',
  styleUrls: ['./app-table.component.scss']
})
export class AppTableComponent implements OnInit {

  list = [
    {
        'id': 3,
        'purchase_order_id': 1,
        'product_id': 46,
        'cost': 8400,
        'cost_with_tax': 9072,
        'price': 14000,
        'price_with_tax': 15120,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 30,
        'monthly_order_count': 0,
        'weekly_order_count': 0,
        'monthly_order_amount': 0,
        'public_stock': -1,
        'accumulated_sales_composition': '98.17',
        'sales_rank': 'C',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 46,
            'combination_id': 0,
            'colorme_id': 100079919,
            'supplier_id': 0,
            'model_number': '990-23727001-X',
            'supplier_model_number': null,
            'product_name': 'CATWORTH/レザーシューズ/ホワイト/22.0～22.5cm',
            'image_uri': '/kurashicom-images/shop/2017-03-16/f9771676b7510a3de2b8839abd4dc624.jpg',
            'display_state': 'published',
            'state': 'active',
            'cost': 8400,
            'markup': 0,
            'price': 14000,
            'discount_price': null,
            'members_price': 14000,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 1,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-04-03 09:06:36',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-15 15:59:51',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 9072,
            'price_with_tax': 15120,
            'price_with_tax_formatted': '15,120円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 15120
        }
    },
    {
        'id': 2,
        'purchase_order_id': 1,
        'product_id': 44,
        'cost': 8400,
        'cost_with_tax': 9072,
        'price': 14000,
        'price_with_tax': 15120,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 8,
        'monthly_order_count': 2,
        'weekly_order_count': 0,
        'monthly_order_amount': 30240,
        'public_stock': -1,
        'accumulated_sales_composition': '94.69',
        'sales_rank': 'B',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 44,
            'combination_id': 0,
            'colorme_id': 100080128,
            'supplier_id': 0,
            'model_number': '990-23727003-X',
            'supplier_model_number': null,
            'product_name': 'CATWORTH/レザーシューズ/ホワイト/24.0～24.5cm',
            'image_uri': '/kurashicom-images/shop/2017-03-16/87d0c07f005187014008b9675ce64a97.jpg',
            'display_state': 'published',
            'state': 'active',
            'cost': 8400,
            'markup': 0,
            'price': 14000,
            'discount_price': null,
            'members_price': 14000,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 0,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-06-05 09:02:20',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-15 16:01:30',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 9072,
            'price_with_tax': 15120,
            'price_with_tax_formatted': '15,120円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 15120
        }
    },
    {
        'id': 1,
        'purchase_order_id': 1,
        'product_id': 33,
        'cost': 6888,
        'cost_with_tax': 7439,
        'price': 12300,
        'price_with_tax': 13284,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 189,
        'monthly_order_count': 0,
        'weekly_order_count': 0,
        'monthly_order_amount': 0,
        'public_stock': -1,
        'accumulated_sales_composition': '98.17',
        'sales_rank': 'C',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 33,
            'combination_id': 0,
            'colorme_id': 100336164,
            'supplier_id': 0,
            'model_number': '990-27734003-X',
            'supplier_model_number': null,
            'product_name': '※※【今季終了】CALZANOR/ツイストストラップ/ウェッジソールサンダル（ネイビー・36サイズ）',
            'image_uri': '/kurashicom-images/shop/2016-05-11/8ee547bdc58db93c889618b7460dd21d.jpg',
            'display_state': 'published',
            'state': 'active',
            'cost': 6888,
            'markup': 0,
            'price': 12300,
            'discount_price': null,
            'members_price': 12300,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 3,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-05-26 09:02:24',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-22 11:21:12',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 7439,
            'price_with_tax': 13284,
            'price_with_tax_formatted': '13,284円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 13284
        }
    }
  ];

  constructor() { }

  ngOnInit() {
  }

}
