import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-table',
  templateUrl: './app-table.component.html',
  styleUrls: ['./app-table.component.scss']
})
export class AppTableComponent implements OnInit {

  list = [
    {
        'id': 3,
        'purchase_order_id': 1,
        'product_id': 46,
        'cost': 8400,
        'cost_with_tax': 9072,
        'price': 14000,
        'price_with_tax': 15120,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 30,
        'monthly_order_count': 0,
        'weekly_order_count': 0,
        'monthly_order_amount': 0,
        'public_stock': -1,
        'accumulated_sales_composition': '98.17',
        'sales_rank': 'C',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 46,
            'combination_id': 0,
            'colorme_id': 100079919,
            'supplier_id': 0,
            'model_number': '990-23727001-X',
            'supplier_model_number': null,
            'product_name': 'CATWORTH/レザーシューズ/ホワイト/22.0～22.5cm',
            'product_content': '<img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2017-03-16/bc8459138b9c6c3565cdd6c4af4bbbbf.jpg\"><br>\n<h2 class=\"mediumTitle\">数あるレザーシューズのなかで、私たちがこれだ！と思えた靴。</h2><br>\nCATWORTHは、世界最大級のダンスアカデミーの靴も手がける由緒あるブランドです。\n<br><br>イギリスの職人がひとつひとつ丁寧に仕上げたシンプルで洗練された靴は、英国が支援している英国ロイヤルバレエ団の正式シューズとしても使用されています。\n<br><br>柔らかくしなやかな牛革素材と丁寧な縫製で作られた靴は、馴染みやすくはき心地も抜群なんですよ。\n<br><br><p style=\"color:#999999; font-size:90%; line-height:1.3;\">※写真は6サイズを使用しています。</p>\n<br><br><br>\n<h2 class=\"mediumTitle\">足首がきれいに見える履き口のカット。ホワイトはカジュアルな服装を爽やかにまとめます。</h2><br>\n足首が出る高さがちょうどよく、ゆるやかな履き口のカーブのおかげか、足先まで女性らしく決まります。\n<br><br>一年を通してコーディネートを軽やかな印象にしてくれるホワイトの革靴。足元が明るいだけで、一気に爽やかな印象に。\n<br><br>コンパクトなデザインなので足元がすっきりと見え、どんなパンツにも合わせやすいですよ。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_2_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（モデル身長：165cm、トップス：COMOLI、パンツ：Phlannel、スカーフ：Alexander Lee Chang、アクセサリー：ブランド不明）</p>\n<br>ガウチョパンツと合わせたときの相性も抜群です。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_9_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（パンツ：FLW、バッグ：ブランド不明）</p>\n<br><br><h2 class=\"mediumTitle\">ほどよい高さのヒールがあるから、お出かけのきちんとコーデにも使える。</h2><br>\n1.2cmのヒールとマットな革の色味は、ロングスカートのような女性らしい服装にもよく合います。\n<br><br>カジュアルにはもちろん、ちょっとおしゃれして行きたい場所にも履いていけるのは、心強いですね。\n\n\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_3_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：SOSO PHLANNEL、スカート：DRESSTERIOR、ハット：Ecur-Andino、アクセサリー：ブランド不明）</p>\n<br><br><br><h2 class=\"mediumTitle\">オールホワイトコーデにもぴったり。</h2><br>\n\nトップス、ボトムス共にホワイトや淡い色でまとめたとき、足元も白にするのも春らしくていいですね。\n<br><br>全身を淡いトーンでまとめると優しい印象になります。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_5_2_2.jpg\">\n\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：UNIQLO、パンツ：ADAM ET ROPE、バッグ：Encachette、アクセサリー：ブランド不明）</p>\n\n<br><br><h2 class=\"mediumTitle\">すっと履ける、駆け出せる。やわらかい牛革の軽やかさ。</h2><br>\n\n柔らかい牛革を使用しているので、紐をむすんだままでも、脱ぎ履きがしやすいです。\n<br><br>足の両サイド部分と中敷きに薄くクッション素材が入っているので、足にフィットしつい毎日履きたくなる履き心地。\n<br><br>足を入れると、ふわふわとしていて素足で履いてもとても気持ちが良いんです。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2017-03-16/a69bf66f06cf72decf015f6300d79755.jpg\"><br>\nとても軽くて、サッと走り出せそうなほど足に馴染んでくれます。<br><br>\nどんなコーディネートにも合わせやすく、履き心地も抜群なレザーシューズ。\n<br><br>この靴と一緒にたくさんお出かけしてくださいね。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_1_2.jpg\">\n<br><br>\nmodel：写真家・中川正子<br>photo：平本泰淳、クラシコム(1.6枚目)<br>\n※このコンテンツの著作権は株式会社クラシコムが保有し、肖像権についてはモデルご本人（中川正子さん）、写真著作権については平本泰淳が保有しております。無断でのコピー、転載、転用は固くお断りいたします。\n\n<br><br><br><h2 class=\"titleIconComment\">サイズ選びのコツ。</h2><br>\n\nこちらのサイズはUKサイズ4です。通常、日本サイズで22.0～22.5cmを履いている方におすすめしております。\n<br><br>普段履いている靴の日本サイズを目安にジャストかワンサイズ上をお選びください。 厚手のソックスやタイツなどを履く場合は、ワンサイズ上をお勧めします。 <br><br>※サイズの詳細はインフォメーションをご確認下さい。\n\n<br><br><h2>◎スタッフが履いてみました！◎<br></h2>「パンプスのときは、いつもより一つ下のサイズで」「足の甲が高い私は、こういうときは一つ上のサイズ」など、靴を買うときにちょっと気になることを、それぞれ異なる3人のスタッフが履いてみたレビューをお届けします。\n<br><br>\n<a href=\"https://hokuohkurashi.com/note/97588\"><font color=\"blue\">>> 続きを読む</font></a>\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/review_shoes_wata_001.jpg\">\n\n<br><br><br><strong>【ご注文の前に、一度ご確認ください。】</strong>\n<br>\n<br>◎以下の場合には、お客さまのご都合によるご返品は、基本的に承りかねますことご理解いただけますようお願い申し上げます。\n<br><br>・一度ご使用になられた場合、またその形跡のある商品、タグを外された場合。\n<br>・お客様の責任で、商品が破損しているもの。\n<br>・クリーニングに出されたり、洗濯された商品。\n<br>・返品のご連絡がないまま返送された商品。\n<br>・商品到着より7日経過後にご連絡をいただいた商品。\n<br>・返品受付後（当店よりご連絡後）7日をすぎての荷物が到着した場合。\n\n<br><br><br><strong>【靴ひもの仕様変更について】</strong>\n<br><br>\n※2017年3月に靴ひもの仕様が変更されました。平紐から丸紐へ変わっております。\n<br>\n※上記のスタッフによるサイズのレビューは、旧仕様で撮影しております。\n\n\n<br><br><br><h2><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/point.gif\" align=\"left\" vspace=\"2\" alt=\"info\">インフォメーション</h2><table class=\"block\"><tr><td class=\"blocka\">メーカー</td><td class=\"blockb\">CATWORTH/キャットワース</td></tr><tr><td class=\"blocka\">生産国</td><td class=\"blockb\">イギリス</td></tr><tr><td class=\"blocka\">材質</td><td class=\"blockb\">表：牛革<br>内側の素材：ポリエステル、綿<br>底材：ゴム<br>中敷材：牛革<br>紐素材：綿</td></tr><tr><td class=\"blocka\">サイズcm</td><td class=\"blockb\">ヒール：1.2<br>足幅:8.2(一番広い部分)<br>靴底から上までの高さ:8<br>生地の厚み：0.2</td></tr>\n<tr><td class=\"blocka\">重量g(両足)</td><td class=\"blockb\">279</td></tr>\n</table>\n\n<br><div class=\"list\"><h2>CATWORTH/キャットワースについて</h2>イギリスの職人がひとつひとつ丁寧に仕上げた特別な靴です。本革仕様の靴は、履きやすく馴染みやすいのが特徴。全ての商品を英国ノーサンプトンの自社工場で生産している。\n\n</div>\n<br clear=\"all\">',
            'image_uri': '/kurashicom-images/shop/2017-03-16/f9771676b7510a3de2b8839abd4dc624.jpg',
            'display_state': 'published',
            'state': 'active',
            'preview_token': 'AUOx3C86bIrPbAuna6ZqpUNOw4E3AitNM2S5tLLgp7tLfV5t5wC7VR6ztbZp',
            'cost': 8400,
            'markup': 0,
            'price': 14000,
            'discount_price': null,
            'members_price': 14000,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 1,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-04-03 09:06:36',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-15 15:59:51',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 9072,
            'price_with_tax': 15120,
            'price_with_tax_formatted': '15,120円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 15120
        }
    },
    {
        'id': 2,
        'purchase_order_id': 1,
        'product_id': 44,
        'cost': 8400,
        'cost_with_tax': 9072,
        'price': 14000,
        'price_with_tax': 15120,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 8,
        'monthly_order_count': 2,
        'weekly_order_count': 0,
        'monthly_order_amount': 30240,
        'public_stock': -1,
        'accumulated_sales_composition': '94.69',
        'sales_rank': 'B',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 44,
            'combination_id': 0,
            'colorme_id': 100080128,
            'supplier_id': 0,
            'model_number': '990-23727003-X',
            'supplier_model_number': null,
            'product_name': 'CATWORTH/レザーシューズ/ホワイト/24.0～24.5cm',
            'product_content': '<img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2017-03-16/5d9f3ea31cb0eeb0f46a837a20fc0a88.jpg\"><br>\n<h2 class=\"mediumTitle\">数あるレザーシューズのなかで、私たちがこれだ！と思えた靴。</h2><br>\nCATWORTHは、世界最大級のダンスアカデミーの靴も手がける由緒あるブランドです。\n<br><br>イギリスの職人がひとつひとつ丁寧に仕上げたシンプルで洗練された靴は、英国が支援している英国ロイヤルバレエ団の正式シューズとしても使用されています。\n<br><br>柔らかくしなやかな牛革素材と丁寧な縫製で作られた靴は、馴染みやすくはき心地も抜群なんですよ。\n<br><br><br>\n<h2 class=\"mediumTitle\">足首がきれいに見える履き口のカット。ホワイトはカジュアルな服装を爽やかにまとめます。</h2><br>\n足首が出る高さがちょうどよく、ゆるやかな履き口のカーブのおかげか、足先まで女性らしく決まります。\n<br><br>一年を通してコーディネートを軽やかな印象にしてくれるホワイトの革靴。足元が明るいだけで、一気に爽やかな印象に。\n<br><br>コンパクトなデザインなので足元がすっきりと見え、どんなパンツにも合わせやすいですよ。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_2_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（モデル身長：165cm、トップス：COMOLI、パンツ：Phlannel、スカーフ：Alexander Lee Chang、アクセサリー：ブランド不明）</p>\n<br>ガウチョパンツと合わせたときの相性も抜群です。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_9_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（パンツ：FLW、バッグ：ブランド不明）</p>\n<br><br><h2 class=\"mediumTitle\">ほどよい高さのヒールがあるから、お出かけのきちんとコーデにも使える。</h2><br>\n1.2cmのヒールとマットな革の色味は、ロングスカートのような女性らしい服装にもよく合います。\n<br><br>カジュアルにはもちろん、ちょっとおしゃれして行きたい場所にも履いていけるのは、心強いですね。\n\n\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_3_2.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：SOSO PHLANNEL、スカート：DRESSTERIOR、ハット：Ecur-Andino、アクセサリー：ブランド不明）</p>\n<br><br><br><h2 class=\"mediumTitle\">オールホワイトコーデにもぴったり。</h2><br>\n\nトップス、ボトムス共にホワイトや淡い色でまとめたとき、足元も白にするのも春らしくていいですね。\n<br><br>全身を淡いトーンでまとめると優しい印象になります。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_5_2_2.jpg\">\n\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：UNIQLO、パンツ：ADAM ET ROPE、バッグ：Encachette、アクセサリー：ブランド不明）</p>\n\n<br><br><h2 class=\"mediumTitle\">すっと履ける、駆け出せる。やわらかい牛革の軽やかさ。</h2><br>\n\n柔らかい牛革を使用しているので、紐をむすんだままでも、脱ぎ履きがしやすいです。\n<br><br>足の両サイド部分と中敷きに薄くクッション素材が入っているので、足にフィットしつい毎日履きたくなる履き心地。\n<br><br>足を入れると、ふわふわとしていて素足で履いてもとても気持ちが良いんです。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2017-03-16/82108f8390fa4243a993005d13acbeff.jpg\"><br>\nとても軽くて、サッと走り出せそうなほど足に馴染んでくれます。<br><br>\nどんなコーディネートにも合わせやすく、履き心地も抜群なレザーシューズ。\n<br><br>この靴と一緒にたくさんお出かけしてくださいね。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/catworth_white_1_2.jpg\">\n<br><br>\nmodel：写真家・中川正子<br>photo：平本泰淳、クラシコム(1.6枚目)<br>\n※このコンテンツの著作権は株式会社クラシコムが保有し、肖像権についてはモデルご本人（中川正子さん）、写真著作権については平本泰淳が保有しております。無断でのコピー、転載、転用は固くお断りいたします。\n\n<br><br><br><strong><span style=\"font-size:large;\" class=\"fontlarge\">サイズ選びのコツ。</span></strong><br><br>\n\nこちらのサイズはUKサイズ6です。通常、日本サイズで24.0～24.5cmを履いている方におすすめしております。\n<br><br>普段履いている靴の日本サイズを目安にジャストかワンサイズ上をお選びください。 厚手のソックスやタイツなどを履く場合は、ワンサイズ上をお勧めします。  <br><br>※サイズの詳細はインフォメーションをご確認下さい。\n\n\n<br><br><h2>◎スタッフが履いてみました！◎<br></h2>「パンプスのときは、いつもより一つ下のサイズで」「足の甲が高い私は、こういうときは一つ上のサイズ」など、靴を買うときにちょっと気になることを、それぞれ異なる3人のスタッフが履いてみたレビューをお届けします。\n\n<br>\n<br>\n<a href=\"https://hokuohkurashi.com/note/97588\"><font color=\"blue\">>> 続きを読む</font></a>\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/review_shoes_wata_001.jpg\">\n\n\n<br><br><br><strong>【ご注文の前に、一度ご確認ください。】</strong>\n<br>\n<br>◎以下の場合には、お客さまのご都合によるご返品は、基本的に承りかねますことご理解いただけますようお願い申し上げます。\n<br><br>・一度ご使用になられた場合、またその形跡のある商品、タグを外された場合。\n<br>・お客様の責任で、商品が破損しているもの。\n<br>・クリーニングに出されたり、洗濯された商品。\n<br>・返品のご連絡がないまま返送された商品。\n<br>・商品到着より7日経過後にご連絡をいただいた商品。\n<br>・返品受付後（当店よりご連絡後）7日をすぎての荷物が到着した場合。\n<br><br><br><strong>【靴ひもの仕様変更について】</strong>\n<br><br>\n※2017年3月に靴ひもの仕様が変更されました。平紐から丸紐へ変わっております。\n<br>\n※上記のスタッフによるサイズのレビューは、旧仕様で撮影しております。\n\n\n\n<br><br><br><h2><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/point.gif\" align=\"left\" vspace=\"2\" alt=\"info\">インフォメーション</h2><table class=\"block\"><tr><td class=\"blocka\">メーカー</td><td class=\"blockb\">CATWORTH/キャットワース</td></tr><tr><td class=\"blocka\">生産国</td><td class=\"blockb\">イギリス</td></tr><tr><td class=\"blocka\">材質</td><td class=\"blockb\">表：牛革<br>内側の素材：ポリエステル、綿<br>底材：ゴム<br>中敷材：牛革<br>紐素材：綿</td></tr><tr><td class=\"blocka\">サイズcm</td><td class=\"blockb\">ヒール：1.2<br>足幅:8.5(一番広い部分)<br>靴底から上までの高さ:8<br>生地の厚み：0.2</td></tr>\n<tr><td class=\"blocka\">重量g(両足)</td><td class=\"blockb\">326</td></tr>\n</table>\n\n<br><div class=\"list\"><h2>CATWORTH/キャットワースについて</h2>イギリスの職人がひとつひとつ丁寧に仕上げた特別な靴です。本革仕様の靴は、履きやすく馴染みやすいのが特徴。全ての商品を英国ノーサンプトンの自社工場で生産している。\n</div>\n<br clear=\"all\">',
            'image_uri': '/kurashicom-images/shop/2017-03-16/87d0c07f005187014008b9675ce64a97.jpg',
            'display_state': 'published',
            'state': 'active',
            'preview_token': '8QQch25943EKAIMCV4lyOETt5IQVmgxNXHBkHuJH7zUMkKh0XsKwg2wR31IQ',
            'cost': 8400,
            'markup': 0,
            'price': 14000,
            'discount_price': null,
            'members_price': 14000,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 0,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-06-05 09:02:20',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-15 16:01:30',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 9072,
            'price_with_tax': 15120,
            'price_with_tax_formatted': '15,120円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 15120
        }
    },
    {
        'id': 1,
        'purchase_order_id': 1,
        'product_id': 33,
        'cost': 6888,
        'cost_with_tax': 7439,
        'price': 12300,
        'price_with_tax': 13284,
        'purchase_order_count': 0,
        'subtotal': 0,
        'subtotal_with_tax': 0,
        'stored_count': 0,
        'unstored_count': 0,
        'stock_mail_count': 189,
        'monthly_order_count': 0,
        'weekly_order_count': 0,
        'monthly_order_amount': 0,
        'public_stock': -1,
        'accumulated_sales_composition': '98.17',
        'sales_rank': 'C',
        'created_at': '2017-06-26 17:07:10',
        'updated_at': '2017-06-26 17:07:10',
        'deleted_at': null,
        'product': {
            'id': 33,
            'combination_id': 0,
            'colorme_id': 100336164,
            'supplier_id': 0,
            'model_number': '990-27734003-X',
            'supplier_model_number': null,
            'product_name': '※※【今季終了】CALZANOR/ツイストストラップ/ウェッジソールサンダル（ネイビー・36サイズ）',
            'product_content': '<img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/7e2289e696f7af7f9c85105223097345.jpg\"><br><h2 class=\"mediumTitle\">夏らしいウェッジソールで疲れない、走れるサンダル！</h2><br>\n\n\n夏らしい涼しさが漂うウェッジソール。スペインの代表的なリゾートシューズのブランド・カルザノール社からサンダルが入荷しました。\n<br><br>\n職人がひとつひとつ手作りで仕上げたジュート（麻）を編み上げたソールは、地面との間のやわらかなクッションとして足裏にフィットし、疲れにくく走れちゃうほどのサンダルです！\n\n<br><br>定番の形で、普段着にも夏のリゾートにも合うウェッジソールサンダル。履いてみたかった！という方におすすめの一足です。\n\n<br><br><br>\n<h2 class=\"mediumTitle\">リピート率の高い、歩きやすさのヒミツ。</h2><br>\nソールの高さは9cm、でも歩きやすいヒミツは素材のジュートと、その造りにあります！\n<br><br>天然のジュート（麻）をハンドステッチで編み上げたソールだから、足裏に負担がかかりにくく、素足にもきもちいいんです。\n<br><br>足の甲にかかるストラップは太めで、しっかりと2箇所ホールドしてくれているから安心ですね。\n\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/8fe9f5a80bc67afd0d120d3a4d018e6a.jpg\">\n<br>\nソールの裏側は滑りにくいラバー素材。「これなら走れる！」とスタッフたちも試していましたよ。何度もリピートされる方がとっても多い理由がわかりますね。 \n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/e680281990cab1de2dbca552cfbe75fc.jpg\">\n<br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-11/c0cda3e14d93074745c772fdcd3f9ed0.jpg\"><p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：無印良品、ボトム：UNIQLO、バッグ：<a href=\"https://hokuohkurashi.com/?pid=100065463\">Larone</a>）</p>\n\n<br><br><br>\n<h2 class=\"mediumTitle\">普段着から、リゾートまで。<br>どんなファッションにもあうから夏の間は大活躍！</h2><br>\n\n夏の普段着も、カルザノールのサンダルを履けばグッとおしゃれに、そして涼やかな印象です。ちょっとそこまでの、ボーダーとデニムスタイルにも似合いますね。\n\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/05af1180dfcd0d74c7b0aa5320ad4a59.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（トップス：ORCIVAL、ボトム：ORCIVAL、眼鏡：MOSCOT Tokyo、バッグ：Herve Chapelier）</p><br>\nもちろん夏のお出かけにもぴったりです！\n<br><br>オールインワンのリラックスしたスタイルにも、ネイビーのツイストストラップが引き締めてくれていますね。<br><br>麦わら帽子やかごバッグとの相性はばつぐんです！\n\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/e980481bc8c1f3ff1cac11c356a5d344.jpg\">\n<p style=\"color:#999999; font-size:90%; line-height:1.3;\">（オールインワン：LE GLAZIK、ボウタイスカーフ：coen、バッグ：CATERINA BERTINI）</p>\n\n<br>過ごしやすく、見た目にも夏らしいウェッジソールは一足ほしいですよね。 \n<br><br>歩きやすさにも定評のあるカルザノールのサンダルなら、安心してワードローブに取り入れられそうです。 \n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/1a9c610d86261bbc7d04a2794eac6fb3.jpg\">\n\n<br><br><br><h2 class=\"mediumTitle\">サイズ選びについて</h2><br>\nサイズは36、37の2つ。日本サイズでは、36＝23〜23.5cm、37＝23.5〜24.0cmとなっています。\n<br><br>素足で履くものですので、普段履いている日本サイズのスニーカーや革靴などよりは、ワンサイズ<strong>「小さめ」</strong>をお選びすることをおすすめします。\n<br><br>サンダルは、かかとがソールからすこし出るか、ちょうどぴったりくらいのサイズですとフィットして履くことができるそうです。\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-11/804cb6c5198897110769816e60df5071.jpg\">\n\n<br><br><h2>＜スタッフのサイズ選び＞</h2><br>\n◎スタッフN◎\n<br>\nスニーカーサイズ：24.0cm\n<br>パンプスサイズ：24.0cm\n<br>このサンダルのジャストサイズ：36\n<br>「甲の幅が広くて高い、\"甲高幅広\"の足ですが、このサンダルでは1サイズ小さめの方がとてもフィットしています。きつすぎず、ヌバッグの革がだんだんなじんできそうです。」\n\n<br><br>\n◎スタッフT◎\n<br>\nスニーカーサイズ：23.5cm\n<br>パンプスサイズ：23.0cm\n<br>このサンダルのジャストサイズ：36\n<br>「かかとは2〜3mmほど余りますが、わたしは推奨サイズの36がぴったりでした。バックストラップがあるからしっかりホールドされているし、甲の幅もジャストです。ピタッとしているよりも少し余裕のあるほうが好きなので、わたしは日本サイズの36で大丈夫でした。」\n\n<br><br><br><h2 class=\"titleIconComment\">【スタッフ着用レビュー】こういうサンダル欲しかった！スタッフが履いてみました。</h2><br>\n\nウェッジソールサンダルがちょうど欲しかった！という二人のスタッフが、この夏サンダルとあわせてみたい服を着てみました。サイズ選びについても聞いてみましたので、ご参考になるかもしれません。\n\n<br><br>\n<a href=\"https://hokuohkurashi.com/note/100529\"><font color=\"blue\">>> 続きを読む</font></a>\n<br><br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-11/f478472bf6588325845765aa1496ead1.jpg\">\n\n<br><br><br><h2 class=\"mediumTitle\">【本商品について】</h2><br>\n製品の製造工程上、以下の状態は良品とさせていただきます。\n<br>・ヒール部分に編み込まれたジュート（麻）の間に黒っぽいものが付着している場合があります。これは熱で溶かしたゴムソールを圧着してつけるために麻の間からゴムが流れでてしまうためです。汚れではございません。\n<br>・ジュート（麻）の編み始めと編み終わりが飛び出ている場合があります。バスク地方に古くから伝わる伝統的製法で生産されており、接着剤を使用していないためです。着用に違和感があるときは、マイナスドライバー等で押し込むことによって簡単にお直しいただけます。\n<br>・手作業で麻紐を巻きつけていくため、左右のかかと最後尾の高さが多少違うことがございます。\n\n<br><br>上記につきましては、不良商品対象外とさせていただきます。さらに卸元の検品済となりますため、こうした理由での「当店不手際による返品、交換」はお受けすることができかねますことをご理解いただけますようお願いいたします。 \n\n<br><br>ジュート（麻）の間から出たゴムの例\n<br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/4465a5e1dd38ac3a75fd652d570bf372.jpg\">\n\n<br>編み始めと編み終わりの例\n<br><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/shop/2016-05-10/616e4a6d34348adac59e2265698e8d9b.jpg\">\n\n<br><br>model：香菜子\n※このコンテンツの著作権は株式会社クラシコムが保有し、肖像権については所属事務所（friday）が保有しております。無断でのコピー、転載、転用は固くお断りいたします。\n\n<br><br>stylist：福田麻琴\n<br><br><p style=\"color:#999999; font-size:90%; line-height:1.3;\">＜本ページで使用した衣料品問い合わせ先＞※連絡先のないものはスタイリスト私物となります。\b※価格は税抜き記載です。\n\n\n<br><br>・写真5枚目　トップス：ORCIVAL 11,000円、ボトム：ORCIVAL 13,800円（ともにBshop/03-6427-3710）、眼鏡 27,000円（MOSCOT Tokyo/03-6434-1070）\n\n<br>・写真6枚目　オールインワン：LE GLAZIK 24,000円（Bshop/03-6427-3710）、ボウタイスカーフ　1,800円（coen/03-6419-4600）、バッグ：CATERINA BERTINI 12,800円（Bshop/03-6427-3710）</p>\n\n\n<br><br><br><h2><img src=\"https://s3-ap-northeast-1.amazonaws.com/kurashicom-images/colorme/PA01034/348/etc/point.gif\" align=\"left\" vspace=\"2\" alt=\"info\">インフォメーション</h2><table class=\"block\">\n<tr><td class=\"blocka\">ブランド</td><td class=\"blockb\">Calzanor/カルザノール - スペイン<br></td></tr>\n<tr><td class=\"blocka\">材質</td><td class=\"blockb\">ストラップ：ヌバック、ソール：ジュート（麻）、アウトソール：ラバー（ゴム）</td></tr>\n<tr><td class=\"blocka\">サイズ</td><td class=\"blockb\">36 （日本サイズ：23〜23.5cm）ソール高さ：9cm\n<br>※モデルの足サイズ：24.5 　モデルは、37を着用しています。\n</td></tr>\n<tr><td class=\"blocka\">生産国</td><td class=\"blockb\">made in spain</td></tr>\n<tr><td class=\"blocka\">注意事項</td><td class=\"blockb\">\n・ジュートを手作業で編み込む際、余った部分が飛び出している場合がございます。\n※マイナスドライバーなどで編み込みの間に飛び出した部分を押し込んで頂くときれいにお直しができます※\n<br>・製造段階での目印がインソールやストラップ内側などに付けられている場合がございます。\n<br>・ジュートの巻き加減により、左右のかかとの高さが若干異なる場合がございます。\n<br>・ジュート(麻)のヒールに熱で溶かしたゴムソールを圧着して付けるため、ヒール側の隙間にゴムが流れ込む場合がございます。\n<br>・ソールの天然ゴムに特有のにおいが感じられる場合がございます。\n<br>※ここでご紹介する商品はすべてメーカーの品質基準をクリアし、国内の正規輸入代理店の厳しい検査基準を満たしたものとなっております。</td></tr></table>\n<br><div class=\"list\"><h2>Calzanor/カルザノールについて</h2>スペインの代表的なリゾートシューズブランド。スペイン北部のイルンという美しいリゾートタウンにファクトリーがある。Calzanorのサンダルはソールからアッパーまで一貫して自社工場で生産されており足型やステッチなどは 今もなお 熟練の職人たちの手作業によってつくられている。</div>\n<br clear=\"all\">',
            'image_uri': '/kurashicom-images/shop/2016-05-11/8ee547bdc58db93c889618b7460dd21d.jpg',
            'display_state': 'published',
            'state': 'active',
            'preview_token': 'CIAq1my1coqhMvUXuIkLDC4eZvSdFeqhTR6sBoVChZ03v9Gsrli2L2PPLpje',
            'cost': 6888,
            'markup': 0,
            'price': 12300,
            'discount_price': null,
            'members_price': 12300,
            'unit': '足',
            'jan_code': '',
            'tag': '',
            'tag_display_until': null,
            'wrappable': 1,
            'max_purchase_count': 0,
            'publish_at': null,
            'unpublish_at': null,
            'real_stock': 3,
            'real_stock_updated_at': '2017-06-21 09:05:06',
            'public_stock': -1,
            'public_stock_updated_at': '2017-05-26 09:02:24',
            'min_stock': 0,
            'min_lot': 0,
            'order_unit': 0,
            'last_sold_at': null,
            'nerest_delivery_date': null,
            'search_engine_title': '',
            'search_engine_description': '',
            'facebook_title': '',
            'created_at': '2016-03-22 11:21:12',
            'updated_at': '2017-06-21 09:05:06',
            'deleted_at': null,
            'cost_with_tax': 7439,
            'price_with_tax': 13284,
            'price_with_tax_formatted': '13,284円',
            'discount_price_with_tax': 0,
            'discount_price_with_tax_formatted': '0円',
            'members_price_with_tax': 13284
        }
    }
  ];

  constructor() { }

  ngOnInit() {
  }

}
